name: pub_riverpod
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  html: ^0.15.3
  json_annotation: ^4.8.1
  pubspec_parse: ^1.2.3
  riverpod_annotation: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  mockito: ^5.4.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  build_verify: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
