name: pub_riverpod
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_easylogger: ^2.3.3
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.6
  fpdart: ^1.0.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  hooks_riverpod: ^2.3.6
  html: ^0.15.3
  http: ^1.1.0
  icons_plus: ^4.0.0
  json_annotation: ^4.8.1
  pubspec_parse: ^1.2.3
  pull_to_refresh: ^2.0.0
  riverpod_annotation: ^2.1.1
  shimmer: ^3.0.0
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  mockito: ^5.4.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  build_verify: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
